Github Repo Link: https://github.com/ayankgp/PyTorch-Deep-Learning-Complete

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

PyTorch Tensors: https://pytorch.org/docs/stable/tensors.html

In [22]:
# scalar

scalar = torch.tensor(7)

print(scalar.shape)
print(scalar)
print(scalar.item()) # --> spits out the actual scalar value from the tensor
print(scalar.dim())

torch.Size([])
tensor(7)
7
0


In [23]:
# vector

vector = torch.tensor([7, 7])

print(vector.shape)
print(vector)
print(vector.dim())

torch.Size([2])
tensor([7, 7])
1


In [24]:
# MATRIX

MATRIX = torch.tensor([
    [7, 8],
    [3, 4]
    ])

print(MATRIX.shape)
print(MATRIX)
print(MATRIX.dim())

torch.Size([2, 2])
tensor([[7, 8],
        [3, 4]])
2


In [26]:
# TENSOR

TENSOR = torch.tensor(
    [[[1,2,3],
      [4,5,6],
      [7,8,9]]]
)

print(TENSOR.shape)
print(TENSOR)
print(TENSOR.dim())

torch.Size([1, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3


In [33]:
TENSOR[0], TENSOR[0][0], TENSOR[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

### Random tensors

Why random tensors?
- The way many neural nets learn is that they start with a tensor of random numbers and adjust them to better represent data.
- neural networks: start with random nums -> look at data -> update random numbers -> look at data -> update random numbers

In [43]:
random_tensor1 = torch.rand(size=[3, 4]) #  BOTH OF THESE 
random_tensor2 = torch.rand(3, 4)   #   ARE CORRECT
random_tensor1, random_tensor2

(tensor([[0.3042, 0.2119, 0.8501, 0.0789],
         [0.5139, 0.9201, 0.6343, 0.1777],
         [0.7602, 0.5730, 0.7934, 0.8755]]),
 tensor([[0.8246, 0.8341, 0.5452, 0.2709],
         [0.1997, 0.0124, 0.3728, 0.2498],
         [0.5406, 0.9649, 0.9608, 0.3423]]))

In [40]:
random_tensor3 = torch.rand(1, 3, 4)
random_tensor3.dim()

3

In [52]:
ones = torch.ones(size=[3, 4])
zeros = torch.zeros(size=[4, 3])
ones, zeros

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]))

In [67]:
one2ten = torch.arange(start=1, end=11, step=1)
one2ten_z = torch.zeros_like(one2ten)
one2ten, one2ten_z

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [79]:
dtype_random_tensor = torch.rand(
    size=[4, 3], 
    dtype=torch.float32,
    device='mps',
    requires_grad=False
)
dtype_random_tensor

tensor([[0.9970, 0.5673, 0.3094],
        [0.0041, 0.7025, 0.7852],
        [0.7711, 0.5345, 0.2261],
        [0.0196, 0.2152, 0.8965]], device='mps:0')

## Tensor common errors in Deep Learning

- tensor not right datatype
- tensor not right shape
- tensor not on right device

In [85]:
float16_random_tensor = torch.rand(
    size=[4, 3], 
    dtype=torch.float32)

float32_random_tensor = torch.rand(
    size=[4, 3], 
    dtype=torch.float64)

float16_random_tensor * float32_random_tensor

tensor([[5.3790e-01, 8.2161e-02, 1.6657e-02],
        [5.4484e-01, 7.6930e-02, 1.7462e-01],
        [4.2221e-04, 2.5905e-01, 2.1816e-01],
        [3.0290e-01, 4.1841e-02, 3.0919e-01]], dtype=torch.float64)

In [86]:
# getting info

float16_random_tensor.dtype, float32_random_tensor.device, float32_random_tensor.shape

(torch.float32, device(type='cpu'), torch.Size([4, 3]))